REM ----------------------------------------------------------------DESEMPACOTADOR--------------------------------------------------------------------------------------
IF NOT EXIST C:\ICC_GCC\DESEMPACOTADOR\ORIGEM MKDIR C:\ICC_GCC\DESEMPACOTADOR\ORIGEM
IF NOT EXIST C:\ICC_GCC\DESEMPACOTADOR\DESTINO MKDIR C:\ICC_GCC\DESEMPACOTADOR\DESTINO
IF NOT EXIST C:\ICC_GCC\DESEMPACOTADOR\REJEITADO MKDIR C:\ICC_GCC\DESEMPACOTADOR\REJEITADO
IF NOT EXIST C:\ICC_GCC\DESEMPACOTADOR\PROCESSADO MKDIR C:\ICC_GCC\DESEMPACOTADOR\PROCESSADO
IF NOT EXIST C:\ICC_GCC\DESEMPACOTADOR\TEMP MKDIR C:\ICC_GCC\DESEMPACOTADOR\TEMP
IF NOT EXIST C:\ICC_GCC\DESEMPACOTADOR\RASTREABILIDADETEMP MKDIR C:\ICC_GCC\DESEMPACOTADOR\RASTREABILIDADETEMP
IF NOT EXIST C:\ICC_GCC\DESEMPACOTADOR\LOGS MKDIR C:\ICC_GCC\DESEMPACOTADOR\LOGS
IF NOT EXIST C:\ICC_GCC\DESEMPACOTADOR MKDIR C:\ICC_GCC\DESEMPACOTADOR
REM ----------------------------------------------------------------IFS----------------------------------------------------------------------------------------------------
REM RASTREABILIDADE / DESMAT_PDF_CONTRATO
IF NOT EXIST C:\ICC_GCC\ACTA2025_IFS\DESMAT\CONTRATO\IFS MKDIR C:\ICC_GCC\ACTA2025_IFS\DESMAT\CONTRATO\IFS
IF NOT EXIST C:\ICC_GCC\ACTA2025_IFS\DESMAT\CONTRATO\IFS\CSV_REJEITADO_RASTREABILIDADE MKDIR C:\ICC_GCC\ACTA2025_IFS\DESMAT\CONTRATO\IFS\CSV_REJEITADO_RASTREABILIDADE
IF NOT EXIST C:\ICC_GCC\ACTA2025_IFS\DESMAT\CONTRATO\IFS\TEMP_RASTREABILIDADE MKDIR C:\ICC_GCC\ACTA2025_IFS\DESMAT\CONTRATO\IFS\TEMP_RASTREABILIDADE
REM RASTREABILIDADE / DESMAT_PDF_NEGOCIO 
IF NOT EXIST C:\ICC_GCC\ACTA2025_IFS\DESMAT\NEGOCIO\IFS MKDIR C:\ICC_GCC\ACTA2025_IFS\DESMAT\NEGOCIO\IFS
IF NOT EXIST C:\ICC_GCC\ACTA2025_IFS\DESMAT\NEGOCIO\IFS\CSV_REJEITADO_RASTREABILIDADE MKDIR C:\ICC_GCC\ACTA2025_IFS\DESMAT\NEGOCIO\IFS\CSV_REJEITADO_RASTREABILIDADE
IF NOT EXIST C:\ICC_GCC\ACTA2025_IFS\DESMAT\NEGOCIO\IFS\TEMP_RASTREABILIDADE MKDIR C:\ICC_GCC\ACTA2025_IFS\DESMAT\NEGOCIO\IFS\TEMP_RASTREABILIDADE
REM RASTREABILIDADE / DESMATFINAL_ACTA05_PRI
IF NOT EXIST C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\PRIM05\IFS MKDIR C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\PRIM05\IFS
IF NOT EXIST C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\PRIM05\IFS\CSV_REJEITADO_RASTREABILIDADE MKDIR C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\PRIM05\IFS\CSV_REJEITADO_RASTREABILIDADE
IF NOT EXIST C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\PRIM05\IFS\TEMP_RASTREABILIDADE MKDIR C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\PRIM05\IFS\TEMP_RASTREABILIDADE
REM RASTREABILIDADE / DESMATFINAL_ACTA06_CONT_CONTRATO
IF NOT EXIST C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\CONT06\CONTRATO\IFS MKDIR C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\CONT06\CONTRATO\IFS
IF NOT EXIST C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\CONT06\CONTRATO\IFS\CSV_REJEITADO_RASTREABILIDADE MKDIR C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\CONT06\CONTRATO\IFS\CSV_REJEITADO_RASTREABILIDADE
IF NOT EXIST C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\CONT06\CONTRATO\IFS\TEMP_RASTREABILIDADE MKDIR C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\CONT06\CONTRATO\IFS\TEMP_RASTREABILIDADE
REM RASTREABILIDADE / DESMATFINAL_ACTA06_CONT_NEGOCIO
IF NOT EXIST C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\CONT06\NEGOCIO\IFS MKDIR C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\CONT06\NEGOCIO\IFS
IF NOT EXIST C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\CONT06\NEGOCIO\IFS\CSV_REJEITADO_RASTREABILIDADE MKDIR C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\CONT06\NEGOCIO\IFS\CSV_REJEITADO_RASTREABILIDADE
IF NOT EXIST C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\CONT06\NEGOCIO\IFS\TEMP_RASTREABILIDADE MKDIR C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\CONT06\NEGOCIO\IFS\TEMP_RASTREABILIDADE
REM RASTREABILIDADE / DESMATFINAL_ACTA06_SEGN
IF NOT EXIST C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\SEGN06\IFS MKDIR C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\SEGN06\IFS
IF NOT EXIST C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\SEGN06\IFS\CSV_REJEITADO_RASTREABILIDADE MKDIR C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\SEGN06\IFS\CSV_REJEITADO_RASTREABILIDADE
IF NOT EXIST C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\SEGN06\IFS\TEMP_RASTREABILIDADE MKDIR C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\SEGN06\IFS\TEMP_RASTREABILIDADE
REM RASTREABILIDADE / DESMATFINAL_ACTA07_CONT_CONTRATO
IF NOT EXIST C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\CONT07\CONTRATO\IFS MKDIR C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\CONT07\CONTRATO\IFS
IF NOT EXIST C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\CONT07\CONTRATO\IFS\CSV_REJEITADO_RASTREABILIDADE MKDIR C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\CONT07\CONTRATO\IFS\CSV_REJEITADO_RASTREABILIDADE
IF NOT EXIST C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\CONT07\CONTRATO\IFS\TEMP_RASTREABILIDADE MKDIR C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\CONT07\CONTRATO\IFS\TEMP_RASTREABILIDADE
REM RASTREABILIDADE / DESMATFINAL_ACTA07_CONT_NEGOCIO
IF NOT EXIST C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\CONT07\NEGOCIO\IFS MKDIR C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\CONT07\NEGOCIO\IFS
IF NOT EXIST C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\CONT07\NEGOCIO\IFS\CSV_REJEITADO_RASTREABILIDADE MKDIR C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\CONT07\NEGOCIO\IFS\CSV_REJEITADO_RASTREABILIDADE
IF NOT EXIST C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\CONT07\NEGOCIO\IFS\TEMP_RASTREABILIDADE MKDIR C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\CONT07\NEGOCIO\IFS\TEMP_RASTREABILIDADE
REM RASTREABILIDADE / DESMATFINAL_ACTA07_SEGN
IF NOT EXIST C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\SEGN07\IFS MKDIR C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\SEGN07\IFS
IF NOT EXIST C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\SEGN07\IFS\CSV_REJEITADO_RASTREABILIDADE MKDIR C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\SEGN07\IFS\CSV_REJEITADO_RASTREABILIDADE
IF NOT EXIST C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\SEGN07\IFS\TEMP_RASTREABILIDADE MKDIR C:\ICC_GCC\ACTA2025_IFS\DESMATFINAL\SEGN07\IFS\TEMP_RASTREABILIDADE
REM ----------------------------------------------------------------ASSINADOR---------------------------------------------------------------------------------------
REM RASTREABILIDADE / ACTA2025_DESMATFINAL_ACTA05PRIM_ASS
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\PRIM05\ZIP MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\PRIM05\ZIP
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\PRIM05\DESEMPACOTADOR\DESTINO MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\PRIM05\DESEMPACOTADOR\DESTINO
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\PRIM05\ASSINADOR\REJEITADOS MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\PRIM05\ASSINADOR\REJEITADOS
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\PRIM05\ASSINADOR\REJEITADOS\ZIP MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\PRIM05\ASSINADOR\REJEITADOS\ZIP
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\PRIM05\ASSINADOR\PROCESSADOS MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\PRIM05\ASSINADOR\PROCESSADOS
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\PRIM05\ASSINADOR\RASTREABILIDADETEMP MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\PRIM05\ASSINADOR\RASTREABILIDADETEMP
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\PRIM05\ASSINADOR\LOGSRASTREABILIDADE MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\PRIM05\ASSINADOR\LOGSRASTREABILIDADE
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\PRIM05\ASSINADOR\REJEITADORASTREABILIDADE MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\PRIM05\ASSINADOR\REJEITADORASTREABILIDADE
REM RASTREABILIDADE / ACTA2025_DESMATFINAL_ACTA06CONT_ASS
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\CONT06\AGENCIA MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\CONT06\AGENCIA
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\CONT06\DESEMPACOTADOR\DESTINO MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\CONT06\DESEMPACOTADOR\DESTINO
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\CONT06\ASSINADOR\REJEITADOS MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\CONT06\ASSINADOR\REJEITADOS
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\CONT06\ASSINADOR\REJEITADOS\ZIP MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\CONT06\ASSINADOR\REJEITADOS\ZIP
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\CONT06\ASSINADOR\PROCESSADOS MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\CONT06\ASSINADOR\PROCESSADOS 
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\CONT06\ASSINADOR\RASTREABILIDADETEMP MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\CONT06\ASSINADOR\RASTREABILIDADETEMP
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\CONT06\ASSINADOR\LOGSRASTREABILIDADE MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\CONT06\ASSINADOR\LOGSRASTREABILIDADE
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\CONT06\ASSINADOR\REJEITADORASTREABILIDADE MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\CONT06\ASSINADOR\REJEITADORASTREABILIDADE
REM RASTREABILIDADE / ACTA2025_DESMATFINAL_ACTA07CONT_ASS
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\CONT07\AGENCIA MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\CONT07\AGENCIA
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\CONT07\DESEMPACOTADOR\DESTINO MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\CONT07\DESEMPACOTADOR\DESTINO
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\CONT07\ASSINADOR\REJEITADOS MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\CONT07\ASSINADOR\REJEITADOS
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\CONT07\ASSINADOR\REJEITADOS\ZIP MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\CONT07\ASSINADOR\REJEITADOS\ZIP
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\CONT07\ASSINADOR\PROCESSADOS MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\CONT07\ASSINADOR\PROCESSADOS
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\CONT07\ASSINADOR\RASTREABILIDADETEMP MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\CONT07\ASSINADOR\RASTREABILIDADETEMP
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\CONT07\ASSINADOR\LOGSRASTREABILIDADE MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\CONT07\ASSINADOR\LOGSRASTREABILIDADE
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\CONT07\ASSINADOR\REJEITADORASTREABILIDADE MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\CONT07\ASSINADOR\REJEITADORASTREABILIDADE
REM RASTREABILIDADE / ACTA2025_DESMATFINAL_ACTA06SEGN_ASS
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\SEGN06\ZIP MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\SEGN06\ZIP
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\SEGN06\DESEMPACOTADOR\DESTINO MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\SEGN06\DESEMPACOTADOR\DESTINO
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\SEGN06\ASSINADOR\REJEITADOS MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\SEGN06\ASSINADOR\REJEITADOS
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\SEGN06\ASSINADOR\REJEITADOS\ZIP MKDIR  C:\ICC_GCC\ACTA2025\DESMATFINAL\SEGN06\ASSINADOR\REJEITADOS\ZIP
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\SEGN06\ASSINADOR\PROCESSADOS MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\SEGN06\ASSINADOR\PROCESSADOS
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\SEGN06\ASSINADOR\RASTREABILIDADETEMP MKDIR  C:\ICC_GCC\ACTA2025\DESMATFINAL\SEGN06\ASSINADOR\RASTREABILIDADETEMP
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\SEGN06\ASSINADOR\LOGSRASTREABILIDADE MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\SEGN06\ASSINADOR\LOGSRASTREABILIDADE
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\SEGN06\ASSINADOR\REJEITADORASTREABILIDADE MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\SEGN06\ASSINADOR\REJEITADORASTREABILIDADE
REM RASTREABILIDADE / ACTA2025_DESMATFINAL_ACTA07SEGN_ASS
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\SEGN07\ZIP MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\SEGN07\ZIP
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\SEGN07\DESEMPACOTADOR\DESTINO MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\SEGN07\DESEMPACOTADOR\DESTINO
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\SEGN07\ASSINADOR\REJEITADOS MKDIR  C:\ICC_GCC\ACTA2025\DESMATFINAL\SEGN07\ASSINADOR\REJEITADOS
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\SEGN07\ASSINADOR\REJEITADOS\ZIP MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\SEGN07\ASSINADOR\REJEITADOS\ZIP
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\SEGN07\ASSINADOR\PROCESSADOS MKDIR  C:\ICC_GCC\ACTA2025\DESMATFINAL\SEGN07\ASSINADOR\PROCESSADOS
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\SEGN07\ASSINADOR\RASTREABILIDADETEMP MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\SEGN07\ASSINADOR\RASTREABILIDADETEMP
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\SEGN07\ASSINADOR\LOGSRASTREABILIDADE MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\SEGN07\ASSINADOR\LOGSRASTREABILIDADE
IF NOT EXIST C:\ICC_GCC\ACTA2025\DESMATFINAL\SEGN07\ASSINADOR\REJEITADORASTREABILIDADE MKDIR C:\ICC_GCC\ACTA2025\DESMATFINAL\SEGN07\ASSINADOR\REJEITADORASTREABILIDADE
REM ---------------------------------------------------------------CONTRATO_ASS---------------------------------------------------------------------------------------
REM RASTREABILIDADE / CONTRATO_NEGOCIO_ASS
IF NOT EXIST C:\ICC_GCC\CONTRATO_ATHIC\NEGOCIO\ZIP\ MKDIR C:\ICC_GCC\CONTRATO_ATHIC\NEGOCIO\ZIP\
IF NOT EXIST C:\ICC_GCC\CONTRATO_ATHIC\NEGOCIO\ASSINADOR\ORIGEM MKDIR C:\ICC_GCC\CONTRATO_ATHIC\NEGOCIO\ASSINADOR\ORIGEM
IF NOT EXIST C:\ICC_GCC\CONTRATO_ATHIC\NEGOCIO\ASSINADOR\REJEITADOS MKDIR C:\ICC_GCC\CONTRATO_ATHIC\NEGOCIO\ASSINADOR\REJEITADOS
IF NOT EXIST C:\ICC_GCC\CONTRATO_ATHIC\NEGOCIO\ASSINADOR\REJEITADOS\ZIP MKDIR C:\ICC_GCC\CONTRATO_ATHIC\NEGOCIO\ASSINADOR\REJEITADOS\ZIP
IF NOT EXIST C:\ICC_GCC\CONTRATO_ATHIC\NEGOCIO\ASSINADOR\PROCESSADOS MKDIR C:\ICC_GCC\CONTRATO_ATHIC\NEGOCIO\ASSINADOR\PROCESSADOS
IF NOT EXIST C:\ICC_GCC\CONTRATO_ATHIC\NEGOCIO\ASSINADOR\CSV_REJEITADO_RASTREABILIDADE MKDIR C:\ICC_GCC\CONTRATO_ATHIC\NEGOCIO\ASSINADOR\CSV_REJEITADO_RASTREABILIDADE
IF NOT EXIST C:\ICC_GCC\CONTRATO_ATHIC\NEGOCIO\ASSINADOR\TEMP_RASTREABILIDADE MKDIR C:\ICC_GCC\CONTRATO_ATHIC\NEGOCIO\ASSINADOR\TEMP_RASTREABILIDADE
REM RASTREABILIDADE / CONTRATO_NEGOCIO_CONCILIADOR_ASS
IF NOT EXIST C:\ICC_GCC\CONTRATO_ATHIC\GOTF\NEGOCIO\CONCILIADOR\ASSINADOR MKDIR C:\ICC_GCC\CONTRATO_ATHIC\GOTF\NEGOCIO\CONCILIADOR\ASSINADOR
IF NOT EXIST C:\ICC_GCC\CONTRATO_ATHIC\GOTF\NEGOCIO\CONCILIADOR\ZIP\ORIGEM MKDIR C:\ICC_GCC\CONTRATO_ATHIC\GOTF\NEGOCIO\CONCILIADOR\ZIP\ORIGEM
IF NOT EXIST C:\ICC_GCC\CONTRATO_ATHIC\GOTF\NEGOCIO\CONCILIADOR\ASSINADOR\REJEITADOS MKDIR C:\ICC_GCC\CONTRATO_ATHIC\GOTF\NEGOCIO\CONCILIADOR\ASSINADOR\REJEITADOS
IF NOT EXIST C:\ICC_GCC\CONTRATO_ATHIC\GOTF\NEGOCIO\CONCILIADOR\ASSINADOR\REJEITADOS\ZIP MKDIR C:\ICC_GCC\CONTRATO_ATHIC\GOTF\NEGOCIO\CONCILIADOR\ASSINADOR\REJEITADOS\ZIP
IF NOT EXIST C:\ICC_GCC\CONTRATO_ATHIC\GOTF\NEGOCIO\CONCILIADOR\ASSINADOR\PROCESSADOS MKDIR C:\ICC_GCC\CONTRATO_ATHIC\GOTF\NEGOCIO\CONCILIADOR\ASSINADOR\PROCESSADOS
IF NOT EXIST C:\ICC_GCC\CONTRATO_ATHIC\GOTF\NEGOCIO\CONCILIADOR\ASSINADOR\CSV_REJEITADO_RASTREABILIDADE MKDIR C:\ICC_GCC\CONTRATO_ATHIC\GOTF\NEGOCIO\CONCILIADOR\ASSINADOR\CSV_REJEITADO_RASTREABILIDADE
IF NOT EXIST C:\ICC_GCC\CONTRATO_ATHIC\GOTF\NEGOCIO\CONCILIADOR\ASSINADOR\TEMP_RASTREABILIDADE MKDIR C:\ICC_GCC\CONTRATO_ATHIC\GOTF\NEGOCIO\CONCILIADOR\ASSINADOR\TEMP_RASTREABILIDADE
REM ----------------------------------------------------------------CONTRATO_IFS-------------------------------------------------------------------------
REM RASTREABILIDADE / CONTRATO
IF NOT EXIST C:\ICC_GCC\CONTRATO_ATHIC\CONTRATO\IFS MKDIR C:\ICC_GCC\CONTRATO_ATHIC\CONTRATO\IFS
IF NOT EXIST C:\ICC_GCC\CONTRATO_ATHIC\CONTRATO\IFS\CSV_REJEITADO_RASTREABILIDADE MKDIR C:\ICC_GCC\CONTRATO_ATHIC\CONTRATO\IFS\CSV_REJEITADO_RASTREABILIDADE
IF NOT EXIST C:\ICC_GCC\CONTRATO_ATHIC\CONTRATO\IFS\TEMP_RASTREABILIDADE MKDIR C:\ICC_GCC\CONTRATO_ATHIC\CONTRATO\IFS\TEMP_RASTREABILIDADE
REM RASTREABILIDADE / CONTRATO_CONCILIADOR
IF NOT EXIST C:\ICC_GCC\CONTRATO_ATHIC\CONTRATO\CONCILIADOR\IFS MKDIR C:\ICC_GCC\CONTRATO_ATHIC\CONTRATO\CONCILIADOR\IFS
IF NOT EXIST C:\ICC_GCC\CONTRATO_ATHIC\CONTRATO\CONCILIADOR\IFS\CSV_REJEITADO_RASTREABILIDADE MKDIR C:\ICC_GCC\CONTRATO_ATHIC\CONTRATO\CONCILIADOR\IFS\CSV_REJEITADO_RASTREABILIDADE
IF NOT EXIST C:\ICC_GCC\CONTRATO_ATHIC\CONTRATO\CONCILIADOR\IFS\TEMP_RASTREABILIDADE MKDIR C:\ICC_GCC\CONTRATO_ATHIC\CONTRATO\CONCILIADOR\IFS\TEMP_RASTREABILIDADE
REM RASTREABILIDADE / CONTRATO_NEGOCIO
IF NOT EXIST C:\ICC_GCC\CONTRATO_ATHIC\NEGOCIO\IFS MKDIR C:\ICC_GCC\CONTRATO_ATHIC\NEGOCIO\IFS
IF NOT EXIST C:\ICC_GCC\CONTRATO_ATHIC\NEGOCIO\IFS\CSV_REJEITADO_RASTREABILIDADE MKDIR C:\ICC_GCC\CONTRATO_ATHIC\NEGOCIO\IFS\CSV_REJEITADO_RASTREABILIDADE
IF NOT EXIST C:\ICC_GCC\CONTRATO_ATHIC\NEGOCIO\IFS\TEMP_RASTREABILIDADE MKDIR C:\ICC_GCC\CONTRATO_ATHIC\NEGOCIO\IFS\TEMP_RASTREABILIDADE
REM RASTREABILIDADE / CONTRATO_NEGOCIO_CONCILIADOR
IF NOT EXIST C:\ICC_GCC\CONTRATO_ATHIC\NEGOCIO\CONCILIADOR\IFS MKDIR C:\ICC_GCC\CONTRATO_ATHIC\NEGOCIO\CONCILIADOR\IFS
IF NOT EXIST C:\ICC_GCC\CONTRATO_ATHIC\NEGOCIO\CONCILIADOR\IFS\CSV_REJEITADO_RASTREABILIDADE MKDIR C:\ICC_GCC\CONTRATO_ATHIC\NEGOCIO\CONCILIADOR\IFS\CSV_REJEITADO_RASTREABILIDADE
IF NOT EXIST C:\ICC_GCC\CONTRATO_ATHIC\NEGOCIO\CONCILIADOR\IFS\TEMP_RASTREABILIDADE MKDIR C:\ICC_GCC\CONTRATO_ATHIC\NEGOCIO\CONCILIADOR\IFS\TEMP_RASTREABILIDADE
REM RASTREABILIDADE / ----------------------------------------------GCCD_IMAG-----------------------------------------------------------------------------------------------------------------------
IF NOT EXIST C:\ICC_GCC\ACTAS_DESMAT\IMAG\ORIGEM MKDIR C:\ICC_GCC\ACTAS_DESMAT\IMAG\ORIGEM
IF NOT EXIST C:\ICC_GCC\ACTAS_DESMAT\IMAG\DESTINO MKDIR C:\ICC_GCC\ACTAS_DESMAT\IMAG\DESTINO
IF NOT EXIST C:\ICC_GCC\ACTAS_DESMAT\IMAG\REJEITADO MKDIR C:\ICC_GCC\ACTAS_DESMAT\IMAG\REJEITADO
IF NOT EXIST C:\ICC_GCC\ACTAS_DESMAT\IMAG\EBCDIC MKDIR C:\ICC_GCC\ACTAS_DESMAT\IMAG\EBCDIC
IF NOT EXIST C:\ICC_GCC\ACTAS_DESMAT\IMAG\TEMPORARIO_RAST MKDIR C:\ICC_GCC\ACTAS_DESMAT\IMAG\TEMPORARIO_RAST
IF NOT EXIST C:\ICC_GCC\ACTAS_DESMAT\IMAG\CSV_REJEITADO_RAST MKDIR C:\ICC_GCC\ACTAS_DESMAT\IMAG\CSV_REJEITADO_RAST
IF NOT EXIST C:\ICC_GCC\ACTAS_DESMAT\IMAG\TEMPORARIO MKDIR C:\ICC_GCC\ACTAS_DESMAT\IMAG\TEMPORARIO
IF NOT EXIST C:\ICC_GCC\ACTAS_DESMAT\IMAG\GCRA MKDIR C:\ICC_GCC\ACTAS_DESMAT\IMAG\GCRA
IF NOT EXIST C:\ICC_GCC\ACTAS_DESMAT\IMAG\TEMPORARIO_RECORTE MKDIR C:\ICC_GCC\ACTAS_DESMAT\IMAG\TEMPORARIO_RECORTE
PAUSE
