REM DESCOMPACTADOR

IF NOT EXIST C:\GCC\DESEMPACOTADOR\Origem mkdir C:\GCC\DESEMPACOTADOR\Origem
IF NOT EXIST C:\GCC\DESEMPACOTADOR\Destino mkdir C:\GCC\DESEMPACOTADOR\Destino
IF NOT EXIST C:\GCC\DESEMPACOTADOR\Rejeitado mkdir C:\GCC\DESEMPACOTADOR\Rejeitado
IF NOT EXIST C:\GCC\DESEMPACOTADOR\Processado mkdir C:\GCC\DESEMPACOTADOR\Processado
IF NOT EXIST C:\GCC\DESEMPACOTADOR\Temp mkdir C:\GCC\DESEMPACOTADOR\Temp
IF NOT EXIST C:\GCC\DESEMPACOTADOR\RastreabilidadeTemp mkdir C:\GCC\DESEMPACOTADOR\RastreabilidadeTemp
IF NOT EXIST C:\GCC\DESEMPACOTADOR\Logs mkdir C:\GCC\DESEMPACOTADOR\Logs
IF NOT EXIST C:\GCC\DESEMPACOTADOR\Rejeitado mkdir C:\GCC\DESEMPACOTADOR\Rejeitado
